"""
GEX Provenance Banner Generator — R4 (Architectural Reform v6.0)

Generates the mandatory provenance disclosure header for all exported documents.
The banner is non-removable — it is document content, not a UI overlay.

Applied to: Banker's Snapshot, IC Pack, CFO Report, any EXPORTED document.
"""

from __future__ import annotations

from datetime import datetime, timezone


def generate_provenance(
    project_name: str,
    company_name: str,
    evidence_summary: dict[str, int],   # {"UNVERIFIED": 2, "SUBMITTED": 3, "CONFIRMED": 14, "AUDITED": 1}
    reviewer_name: str,
    reviewer_title: str,
    review_scope: str,
    review_date: str,
    generated_at: str | None = None,
) -> str:
    """
    Returns a formatted plain-text provenance banner for document headers.

    The banner discloses:
    - Document origin (platform-generated)
    - Evidence verification summary at time of export
    - Named reviewer and scope
    - Machine-generation notice with mandatory human review statement
    """
    if generated_at is None:
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    unverified = evidence_summary.get("UNVERIFIED", 0)
    submitted  = evidence_summary.get("SUBMITTED", 0)
    confirmed  = evidence_summary.get("CONFIRMED", 0)
    audited    = evidence_summary.get("AUDITED", 0)
    total      = unverified + submitted + confirmed + audited

    verified_pct = (
        round(((confirmed + audited) / total) * 100)
        if total > 0 else 0
    )

    lines = [
        "─" * 72,
        "PROVENANCE DISCLOSURE — GreenEarthX Platform",
        "─" * 72,
        f"Project:       {project_name}",
        f"Company:       {company_name}",
        f"Generated:     {generated_at}",
        "",
        "Evidence verification at time of export:",
        f"  Audited:     {audited}  (×1.00 weight)",
        f"  Confirmed:   {confirmed}  (×0.85 weight)",
        f"  Submitted:   {submitted}  (×0.50 weight)",
        f"  Unverified:  {unverified}  (×0.25 weight)",
        f"  → {verified_pct}% of evidence at CONFIRMED or above",
        "",
        f"Reviewed by:   {reviewer_name}",
        f"Title:         {reviewer_title}",
        f"Review scope:  {review_scope.replace('_', ' ').title()}",
        f"Review date:   {review_date}",
        "",
        "NOTICE: This document was generated by the GreenEarthX platform using",
        "data submitted by the project company. It has not been independently",
        "verified beyond the evidence states shown above. It is not a substitute",
        "for institution-specific credit analysis or independent due diligence.",
        "Distribution is subject to the receiving institution's policies.",
        "─" * 72,
    ]

    return "\n".join(lines)


def evidence_summary_from_gates(gate_summaries: list[dict]) -> dict[str, int]:
    """
    Aggregate evidence state counts across all gates into a single summary.
    Input: list of gate summary dicts (from /api/v1/verification/summary/{project_id})
    """
    totals: dict[str, int] = {
        "UNVERIFIED": 0,
        "SUBMITTED":  0,
        "CONFIRMED":  0,
        "AUDITED":    0,
    }
    for gate in gate_summaries:
        for state in totals:
            totals[state] += gate.get(state, 0)
    return totals
