/**
 * Issue codes registry — all 25 validation/consistency issue definitions.
 * Pure data, no logic.
 */
import type { IssueCodeDef } from '../types';

export const ISSUE_CODES: readonly IssueCodeDef[] = [
  {
    issueCode: 'INCONSISTENT_CAPACITY_FLOW',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['CAPACITY_MAIN', 'HOURS_YEAR', 'FLOW_MAIN'],
    messageTemplate: 'Capacity ({CAPACITY_MAIN} {unit}) ≠ Flow ({FLOW_MAIN} {unit}) × Hours ({HOURS_YEAR} h/yr). Δ = {delta} {unit}/yr ({deltaPct}%).',
    resolutionActions: ['Recalculate FLOW_MAIN from CAPACITY_MAIN and HOURS_YEAR', 'Recalculate CAPACITY_MAIN from FLOW_MAIN and HOURS_YEAR', 'Adjust HOURS_YEAR to reconcile'],
    notes: 'Core Rule 9 check, capacity = flow × hours',
  },
  {
    issueCode: 'INCONSISTENT_POWER_FROM_SEC',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FLOW_MAIN', 'SEC_ELEC', 'P_BASE', 'POWER_ELEC'],
    messageTemplate: 'Power ({POWER_ELEC} kW) ≠ P_base ({P_BASE} kW) + Flow ({FLOW_MAIN} kg/h) × SEC ({SEC_ELEC} kWh/kg). Δ = {delta} kW ({deltaPct}%).',
    resolutionActions: ['Recalculate POWER_ELEC from throughput model', 'Adjust SEC_ELEC to match stated power', 'Adjust P_BASE'],
    notes: 'Power = base load + throughput × specific consumption',
  },
  {
    issueCode: 'INCONSISTENT_ANNUAL_ENERGY',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['POWER_ELEC', 'HOURS_YEAR', 'E_YEAR_ELEC'],
    messageTemplate: 'Annual energy ({E_YEAR_ELEC} kWh/yr) ≠ Power ({POWER_ELEC} kW) × Hours ({HOURS_YEAR} h/yr). Δ = {delta} kWh/yr.',
    resolutionActions: ['Recalculate E_YEAR_ELEC = POWER_ELEC × HOURS_YEAR', 'Recalculate POWER_ELEC = E_YEAR_ELEC / HOURS_YEAR'],
    notes: 'Simple energy = power × time check',
  },
  {
    issueCode: 'INCONSISTENT_THERMAL_DUTY',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FLOW_MAIN', 'SEC_TH', 'P_TH_BASE', 'DUTY_TH'],
    messageTemplate: 'Thermal duty ({DUTY_TH} kW) ≠ Q_base ({P_TH_BASE} kW) + Flow ({FLOW_MAIN} kg/h) × SEC_th ({SEC_TH} kWh/kg). Δ = {delta} kW.',
    resolutionActions: ['Recalculate DUTY_TH from throughput model', 'Adjust SEC_TH to match stated duty'],
    notes: 'Thermal duty = base + throughput × SEC',
  },
  {
    issueCode: 'INCONSISTENT_COOLING_POWER',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['COOLING_DUTY', 'COP_COOL', 'P_BASE', 'POWER_ELEC'],
    messageTemplate: 'Cooling power ({POWER_ELEC} kW) ≠ P_base + Q_cool / COP. Expected {expected} kW. Δ = {delta} kW.',
    resolutionActions: ['Recalculate POWER_ELEC = P_BASE + COOLING_DUTY / COP_COOL', 'Adjust COP_COOL', 'Adjust COOLING_DUTY'],
    notes: 'Cooling-driven electrical power check',
  },
  {
    issueCode: 'INCONSISTENT_FUEL_DUTY',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FUEL_DUTY', 'EFF_TH', 'LHV_FUEL', 'FLOW_FUEL'],
    messageTemplate: 'Fuel flow ({FLOW_FUEL} kg/h) ≠ Q / (η × LHV). Expected {expected} kg/h. Δ = {delta} kg/h.',
    resolutionActions: ['Recalculate FLOW_FUEL from FUEL_DUTY, EFF_TH, LHV_FUEL', 'Recalculate FUEL_DUTY from FLOW_FUEL'],
    notes: 'Fuel mass balance: m_fuel = Q / (η × LHV)',
  },
  {
    issueCode: 'INCONSISTENT_STEAM_FLOW',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['STEAM_DUTY', 'DELTAH_STEAM', 'FLOW_STEAM'],
    messageTemplate: 'Steam flow ({FLOW_STEAM} kg/h) ≠ Q / Δh. Expected {expected} kg/h. Δ = {delta} kg/h.',
    resolutionActions: ['Recalculate FLOW_STEAM from STEAM_DUTY and DELTAH_STEAM', 'Recalculate STEAM_DUTY from FLOW_STEAM'],
    notes: 'Steam energy balance: m_steam = Q / Δh',
  },
  {
    issueCode: 'INCONSISTENT_SPLIT',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FLOW_IN', 'RECOVERY', 'FLOW_OUT', 'FLOW_WASTE'],
    messageTemplate: 'Split balance: In ({FLOW_IN} kg/h) ≠ Out ({FLOW_OUT} kg/h) + Waste ({FLOW_WASTE} kg/h). Δ = {delta} kg/h.',
    resolutionActions: ['Recalculate FLOW_OUT and FLOW_WASTE from FLOW_IN and RECOVERY', 'Adjust RECOVERY'],
    notes: 'Mass balance across splitter/separator',
  },
  {
    issueCode: 'INCONSISTENT_REMOVAL',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FLOW_IN', 'REMOVAL_EFF', 'FLOW_OUT', 'FLOW_REMOVED'],
    messageTemplate: 'Removal balance: In ({FLOW_IN} kg/h) ≠ Out ({FLOW_OUT} kg/h) + Removed ({FLOW_REMOVED} kg/h). Δ = {delta} kg/h.',
    resolutionActions: ['Recalculate FLOW_OUT and FLOW_REMOVED from FLOW_IN and REMOVAL_EFF', 'Adjust REMOVAL_EFF'],
    notes: 'Mass balance across removal unit',
  },
  {
    issueCode: 'INCONSISTENT_BESS',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['P_RATED', 'DURATION_H', 'E_STORAGE'],
    messageTemplate: 'BESS energy ({E_STORAGE} kWh) ≠ P_rated ({P_RATED} kW) × Duration ({DURATION_H} h). Δ = {delta} kWh.',
    resolutionActions: ['Recalculate E_STORAGE = P_RATED × DURATION_H', 'Recalculate P_RATED = E_STORAGE / DURATION_H'],
    notes: 'Battery energy = power × duration',
  },
  {
    issueCode: 'INCONSISTENT_GENERATOR',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FLOW_FUEL', 'EFF_ELEC', 'LHV_FUEL', 'POWER_ELEC'],
    messageTemplate: 'Generator power ({POWER_ELEC} kW) ≠ P_base + m_fuel × η × LHV. Expected {expected} kW. Δ = {delta} kW.',
    resolutionActions: ['Recalculate POWER_ELEC from generator model', 'Recalculate FLOW_FUEL from stated power'],
    notes: 'Generator output consistency',
  },
  {
    issueCode: 'INCONSISTENT_STOICH_ELECTROLYSIS',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['FLOW_H2', 'FLOW_H2O', 'FLOW_O2'],
    messageTemplate: 'Electrolysis stoichiometry violated: H₂O ({FLOW_H2O} kg/h) ≠ 9 × H₂ × water_factor, or O₂ ({FLOW_O2} kg/h) ≠ 8 × H₂.',
    resolutionActions: ['Recalculate FLOW_H2O and FLOW_O2 from FLOW_H2 using stoichiometry', 'Adjust WATER_FACTOR'],
    notes: '2H₂O → 2H₂ + O₂ mass basis: 9 kg H₂O per kg H₂, 8 kg O₂ per kg H₂',
  },
  {
    issueCode: 'INCONSISTENT_STOICH_METHANATION',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_CO_IN_KMOL_H', 'F_CO2_IN_KMOL_H', 'F_H2_IN_KMOL_H', 'F_CH4_OUT_KMOL_H', 'F_H2O_OUT_KMOL_H', 'F_H2_OUT_KMOL_H'],
    messageTemplate: 'Methanation molar balance violated. Check CO/CO₂ conversions and H₂/CH₄/H₂O stoichiometry.',
    resolutionActions: ['Recalculate all outlet flows from inlet flows and conversions using SYNTH_STOICH_V1', 'Verify X_CO and X_CO2 are within [0, 1]'],
    notes: 'CO + 3H₂ → CH₄ + H₂O; CO₂ + 4H₂ → CH₄ + 2H₂O',
  },
  {
    issueCode: 'INCONSISTENT_STOICH_METHANOL',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_CO_IN_KMOL_H', 'F_CO2_IN_KMOL_H', 'F_H2_IN_KMOL_H', 'F_MEOH_OUT_KMOL_H', 'F_H2O_OUT_KMOL_H', 'F_H2_OUT_KMOL_H'],
    messageTemplate: 'Methanol synthesis molar balance violated. Check CO/CO₂ conversions and H₂/MeOH/H₂O stoichiometry.',
    resolutionActions: ['Recalculate all outlet flows from inlet flows and conversions', 'Verify X_CO and X_CO2 are within [0, 1]'],
    notes: 'CO + 2H₂ → CH₃OH; CO₂ + 3H₂ → CH₃OH + H₂O',
  },
  {
    issueCode: 'INCONSISTENT_STOICH_DME',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_MEOH_IN_KMOL_H', 'F_DME_OUT_KMOL_H', 'F_H2O_OUT_KMOL_H', 'F_MEOH_OUT_KMOL_H'],
    messageTemplate: 'DME dehydration molar balance violated. Check MeOH conversion and DME/H₂O stoichiometry.',
    resolutionActions: ['Recalculate outlet flows from MeOH conversion', 'Verify X_MEOH is within [0, 1]'],
    notes: '2CH₃OH → CH₃OCH₃ + H₂O',
  },
  {
    issueCode: 'INCONSISTENT_STOICH_AMMONIA',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_N2_IN_KMOL_H', 'F_H2_IN_KMOL_H', 'F_NH3_OUT_KMOL_H', 'F_H2_OUT_KMOL_H'],
    messageTemplate: 'Ammonia synthesis molar balance violated. Check N₂ conversion and H₂/NH₃ stoichiometry.',
    resolutionActions: ['Recalculate outlet flows from N₂ conversion', 'Verify X_N2 is within [0, 1]'],
    notes: 'N₂ + 3H₂ → 2NH₃',
  },
  {
    issueCode: 'INCONSISTENT_STOICH_FT',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_CO_IN_KMOL_H', 'F_H2_IN_KMOL_H', 'F_FT_LIQ_KG_H', 'F_H2O_OUT_KMOL_H', 'F_CO_OUT_KMOL_H'],
    messageTemplate: 'Fischer-Tropsch yield balance violated. Check CO conversion, H₂/CO ratio, and liquid yield.',
    resolutionActions: ['Recalculate outlet flows from CO conversion and yield parameters', 'Verify X_CO, R_H2_CO, and Y_LIQ are consistent'],
    notes: 'CO + R×H₂ → liquid + H₂O (+ byproducts)',
  },
  {
    issueCode: 'INCONSISTENT_POLYMERIZATION',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_MONOMER_IN_KMOL_H', 'F_POLYMER_KG_H', 'F_MONOMER_OUT_KMOL_H'],
    messageTemplate: 'Polymerization mass balance violated. Check monomer conversion, MW, and yield.',
    resolutionActions: ['Recalculate polymer output from monomer conversion, MW, and yield', 'Verify X_MONOMER and YIELD_MASS are within [0, 1]'],
    notes: 'polymer_mass = conv × MW × yield',
  },
  {
    issueCode: 'INCONSISTENT_LOOP_PURGE',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: ['F_RECYCLE_KMOL_H', 'PURGE_FRAC', 'F_PURGE_KMOL_H', 'F_RECYCLE_OUT_KMOL_H'],
    messageTemplate: 'Loop purge balance violated: recycle ({F_RECYCLE_KMOL_H}) ≠ purge + recycle_out. Δ = {delta} kmol/h.',
    resolutionActions: ['Recalculate F_PURGE and F_RECYCLE_OUT from PURGE_FRAC', 'Verify PURGE_FRAC is within [0, 1]'],
    notes: 'purge = recycle × f; recycle_out = recycle - purge',
  },
  {
    issueCode: 'CONNECTION_FLOW_MISMATCH',
    scopeType: 'CONNECTION',
    severityPolicy: 'CONTINUITY',
    keysAffected: ['UPSTREAM_FLOW_KEY', 'DOWNSTREAM_FLOW_KEY'],
    messageTemplate: 'Flow mismatch on connection {connectionId}: upstream ({upstreamValue} {unit}) ≠ downstream ({downstreamValue} {unit}). Δ = {delta} {unit}.',
    resolutionActions: ['Propagate upstream flow to downstream equipment', 'Adjust downstream equipment capacity to match', 'Insert a splitter or mixer node'],
    notes: 'Inter-equipment flow continuity check',
  },
  {
    issueCode: 'INVALID_NEGATIVE_VALUE',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'VALIDATION',
    keysAffected: [],
    messageTemplate: 'Parameter {paramKey} has negative value ({value} {unit}) which is physically invalid.',
    resolutionActions: ['Set value to zero or a positive number', 'Check upstream calculations for sign errors'],
    notes: 'Most physical quantities (flow, power, energy) cannot be negative',
  },
  {
    issueCode: 'INVALID_EFFICIENCY_RANGE',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'VALIDATION',
    keysAffected: ['EFF_TH', 'EFF_ELEC'],
    messageTemplate: 'Efficiency {paramKey} = {value} is outside valid range [0, 1]. Must be a fraction between 0 and 1.',
    resolutionActions: ['Set efficiency to a value between 0 and 1', 'If entered as percentage, divide by 100'],
    notes: 'Efficiencies must be 0 ≤ η ≤ 1',
  },
  {
    issueCode: 'INVALID_COP_RANGE',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'VALIDATION',
    keysAffected: ['COP_COOL'],
    messageTemplate: 'COP ({value}) is outside expected range [1, 10]. Typical industrial COP is 2.5–5.0.',
    resolutionActions: ['Set COP to a realistic value (typically 2.5–5.0)', 'Verify cooling system specification'],
    notes: 'COP must be ≥ 1 by thermodynamics; >10 is unrealistic',
  },
  {
    issueCode: 'MISSING_REQUIRED_INPUTS',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'VALIDATION',
    keysAffected: [],
    messageTemplate: 'Equipment {equipmentId} ({archetypeId}) is missing required input(s): {missingKeys}. Cannot compute derived parameters.',
    resolutionActions: ['Enter values for all required input parameters', 'Apply defaults from the library for this archetype'],
    notes: 'Engine cannot run formulas without all required inputs',
  },
  {
    issueCode: 'OVERDETERMINED_CONFLICT',
    scopeType: 'EQUIPMENT',
    severityPolicy: 'CONSISTENCY',
    keysAffected: [],
    messageTemplate: 'Equipment {equipmentId} has conflicting user-entered values for {conflictingKeys}. The system is overdetermined, one value must be derived or removed.',
    resolutionActions: ['Remove override from one of the conflicting parameters', 'Mark one parameter as DERIVED to let the engine compute it', 'Review which value is the "source of truth"'],
    notes: 'Occurs when user overrides both an input and its derived output',
  },
] as const;
